#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYHOSO")]
	public partial class LINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDuAn(DuAn instance);
    partial void UpdateDuAn(DuAn instance);
    partial void DeleteDuAn(DuAn instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhanVien_DuAn(NhanVien_DuAn instance);
    partial void UpdateNhanVien_DuAn(NhanVien_DuAn instance);
    partial void DeleteNhanVien_DuAn(NhanVien_DuAn instance);
    #endregion
		
		public LINQDataContext() : 
				base(global::QLHS.Properties.Settings.Default.QUANLYHOSOConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DuAn> DuAns
		{
			get
			{
				return this.GetTable<DuAn>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien_DuAn> NhanVien_DuAns
		{
			get
			{
				return this.GetTable<NhanVien_DuAn>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suaduan")]
		public int suaduan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tenduan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string diadiem, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dientich, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ngaybatdau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ngayketthuc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gthd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gttqt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dttc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string file)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan, tenduan, diadiem, dientich, ngaybatdau, ngayketthuc, gthd, gttqt, nth, dttc, file);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suanhanvien")]
		public int suanhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tennhanvien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string capbac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string chucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> trangthai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien, tennhanvien, capbac, chucvu, trangthai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themduan")]
		public int themduan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tenduan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string diadiem, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dientich, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ngaybatdau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ngayketthuc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gthd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gttqt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dttc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string file)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenduan, diadiem, dientich, ngaybatdau, ngayketthuc, gthd, gttqt, nth, dttc, file);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themnhanvien")]
		public int themnhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tennhanvien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string capbac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string chucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> trangthai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tennhanvien, capbac, chucvu, trangthai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoaduan")]
		public int xoaduan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_capbac", IsComposable=true)]
		public string lay_capbac([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_chucvu", IsComposable=true)]
		public string lay_chucvu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_cottenduan", IsComposable=true)]
		public IQueryable<lay_cottenduanResult> lay_cottenduan()
		{
			return this.CreateMethodCallQuery<lay_cottenduanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_cottennhanvien", IsComposable=true)]
		public IQueryable<lay_cottennhanvienResult> lay_cottennhanvien()
		{
			return this.CreateMethodCallQuery<lay_cottennhanvienResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_diadiem", IsComposable=true)]
		public string lay_diadiem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_dientich", IsComposable=true)]
		public string lay_dientich([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_filedinhkiem", IsComposable=true)]
		public string lay_filedinhkiem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_giatrihopdong", IsComposable=true)]
		public System.Nullable<double> lay_giatrihopdong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_giatrithanhquyettoan", IsComposable=true)]
		public System.Nullable<double> lay_giatrithanhquyettoan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_madoitruong", IsComposable=true)]
		public System.Nullable<int> lay_madoitruong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_manguoilaphoso", IsComposable=true)]
		public System.Nullable<int> lay_manguoilaphoso([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_manhanvien", IsComposable=true)]
		public System.Nullable<int> lay_manhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tennhanvien)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tennhanvien).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_ngaybatdau", IsComposable=true)]
		public string lay_ngaybatdau([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_ngayketthuc", IsComposable=true)]
		public string lay_ngayketthuc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_tenduan", IsComposable=true)]
		public string lay_tenduan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_tennhanvien", IsComposable=true)]
		public string lay_tennhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_trangthai", IsComposable=true)]
		public System.Nullable<int> lay_trangthai([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.laybangduan", IsComposable=true)]
		public IQueryable<laybangduanResult> laybangduan()
		{
			return this.CreateMethodCallQuery<laybangduanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.laybangnhanvien", IsComposable=true)]
		public IQueryable<laybangnhanvienResult> laybangnhanvien()
		{
			return this.CreateMethodCallQuery<laybangnhanvienResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem_nam", IsComposable=true)]
		public IQueryable<timkiem_namResult> timkiem_nam([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			return this.CreateMethodCallQuery<timkiem_namResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem_tenduan", IsComposable=true)]
		public IQueryable<timkiem_tenduanResult> timkiem_tenduan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string ten)
		{
			return this.CreateMethodCallQuery<timkiem_tenduanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ten);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_bangduan", IsComposable=true)]
		public IQueryable<lay_bangduanResult> lay_bangduan()
		{
			return this.CreateMethodCallQuery<lay_bangduanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_bangduan1", IsComposable=true)]
		public IQueryable<lay_bangduan1Result> lay_bangduan1()
		{
			return this.CreateMethodCallQuery<lay_bangduan1Result>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DuAn")]
	public partial class DuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDuAn;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private System.Nullable<int> _MaDoiTruong;
		
		private System.Nullable<int> _MaNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		private EntitySet<NhanVien_DuAn> _NhanVien_DuAns;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<NhanVien> _NhanVien1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDuAnChanging(int value);
    partial void OnMaDuAnChanged();
    partial void OnTenDuAnChanging(string value);
    partial void OnTenDuAnChanged();
    partial void OnDiaDiemChanging(string value);
    partial void OnDiaDiemChanged();
    partial void OnDienTichChanging(string value);
    partial void OnDienTichChanged();
    partial void OnNgayBatDauChanging(string value);
    partial void OnNgayBatDauChanged();
    partial void OnNgayKetThucChanging(string value);
    partial void OnNgayKetThucChanged();
    partial void OnGiaTriHopDongChanging(System.Nullable<double> value);
    partial void OnGiaTriHopDongChanged();
    partial void OnGiaTriThanhQuyetToanChanging(System.Nullable<double> value);
    partial void OnGiaTriThanhQuyetToanChanged();
    partial void OnMaDoiTruongChanging(System.Nullable<int> value);
    partial void OnMaDoiTruongChanged();
    partial void OnMaNguoiLapHoSoChanging(System.Nullable<int> value);
    partial void OnMaNguoiLapHoSoChanged();
    partial void OnFileDinhKemChanging(string value);
    partial void OnFileDinhKemChanged();
    #endregion
		
		public DuAn()
		{
			this._NhanVien_DuAns = new EntitySet<NhanVien_DuAn>(new Action<NhanVien_DuAn>(this.attach_NhanVien_DuAns), new Action<NhanVien_DuAn>(this.detach_NhanVien_DuAns));
			this._NhanVien = default(EntityRef<NhanVien>);
			this._NhanVien1 = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this.OnMaDuAnChanging(value);
					this.SendPropertyChanging();
					this._MaDuAn = value;
					this.SendPropertyChanged("MaDuAn");
					this.OnMaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this.OnTenDuAnChanging(value);
					this.SendPropertyChanging();
					this._TenDuAn = value;
					this.SendPropertyChanged("TenDuAn");
					this.OnTenDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this.OnDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem = value;
					this.SendPropertyChanged("DiaDiem");
					this.OnDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this.OnDienTichChanging(value);
					this.SendPropertyChanging();
					this._DienTich = value;
					this.SendPropertyChanged("DienTich");
					this.OnDienTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this.OnGiaTriHopDongChanging(value);
					this.SendPropertyChanging();
					this._GiaTriHopDong = value;
					this.SendPropertyChanged("GiaTriHopDong");
					this.OnGiaTriHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this.OnGiaTriThanhQuyetToanChanging(value);
					this.SendPropertyChanging();
					this._GiaTriThanhQuyetToan = value;
					this.SendPropertyChanged("GiaTriThanhQuyetToan");
					this.OnGiaTriThanhQuyetToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTruong", DbType="Int")]
		public System.Nullable<int> MaDoiTruong
		{
			get
			{
				return this._MaDoiTruong;
			}
			set
			{
				if ((this._MaDoiTruong != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoiTruongChanging(value);
					this.SendPropertyChanging();
					this._MaDoiTruong = value;
					this.SendPropertyChanged("MaDoiTruong");
					this.OnMaDoiTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiLapHoSo", DbType="Int")]
		public System.Nullable<int> MaNguoiLapHoSo
		{
			get
			{
				return this._MaNguoiLapHoSo;
			}
			set
			{
				if ((this._MaNguoiLapHoSo != value))
				{
					if (this._NhanVien1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiLapHoSoChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiLapHoSo = value;
					this.SendPropertyChanged("MaNguoiLapHoSo");
					this.OnMaNguoiLapHoSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this.OnFileDinhKemChanging(value);
					this.SendPropertyChanging();
					this._FileDinhKem = value;
					this.SendPropertyChanged("FileDinhKem");
					this.OnFileDinhKemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_NhanVien_DuAn", Storage="_NhanVien_DuAns", ThisKey="MaDuAn", OtherKey="MaDuAn")]
		public EntitySet<NhanVien_DuAn> NhanVien_DuAns
		{
			get
			{
				return this._NhanVien_DuAns;
			}
			set
			{
				this._NhanVien_DuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DuAn", Storage="_NhanVien", ThisKey="MaDoiTruong", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.DuAns.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.DuAns.Add(this);
						this._MaDoiTruong = value.MaNhanVien;
					}
					else
					{
						this._MaDoiTruong = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DuAn1", Storage="_NhanVien1", ThisKey="MaNguoiLapHoSo", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien1
		{
			get
			{
				return this._NhanVien1.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien1.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien1.Entity = null;
						previousValue.DuAns1.Remove(this);
					}
					this._NhanVien1.Entity = value;
					if ((value != null))
					{
						value.DuAns1.Add(this);
						this._MaNguoiLapHoSo = value.MaNhanVien;
					}
					else
					{
						this._MaNguoiLapHoSo = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhanVien1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanVien_DuAns(NhanVien_DuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = this;
		}
		
		private void detach_NhanVien_DuAns(NhanVien_DuAn entity)
		{
			this.SendPropertyChanging();
			entity.DuAn = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhanVien;
		
		private string _TenNhanVien;
		
		private string _CapBacHienTai;
		
		private string _ChucVuHienTai;
		
		private System.Nullable<int> _TrangThai;
		
		private EntitySet<DuAn> _DuAns;
		
		private EntitySet<DuAn> _DuAns1;
		
		private EntitySet<NhanVien_DuAn> _NhanVien_DuAns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    partial void OnCapBacHienTaiChanging(string value);
    partial void OnCapBacHienTaiChanged();
    partial void OnChucVuHienTaiChanging(string value);
    partial void OnChucVuHienTaiChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public NhanVien()
		{
			this._DuAns = new EntitySet<DuAn>(new Action<DuAn>(this.attach_DuAns), new Action<DuAn>(this.detach_DuAns));
			this._DuAns1 = new EntitySet<DuAn>(new Action<DuAn>(this.attach_DuAns1), new Action<DuAn>(this.detach_DuAns1));
			this._NhanVien_DuAns = new EntitySet<NhanVien_DuAn>(new Action<NhanVien_DuAn>(this.attach_NhanVien_DuAns), new Action<NhanVien_DuAn>(this.detach_NhanVien_DuAns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(200)")]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapBacHienTai", DbType="NVarChar(200)")]
		public string CapBacHienTai
		{
			get
			{
				return this._CapBacHienTai;
			}
			set
			{
				if ((this._CapBacHienTai != value))
				{
					this.OnCapBacHienTaiChanging(value);
					this.SendPropertyChanging();
					this._CapBacHienTai = value;
					this.SendPropertyChanged("CapBacHienTai");
					this.OnCapBacHienTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVuHienTai", DbType="NVarChar(200)")]
		public string ChucVuHienTai
		{
			get
			{
				return this._ChucVuHienTai;
			}
			set
			{
				if ((this._ChucVuHienTai != value))
				{
					this.OnChucVuHienTaiChanging(value);
					this.SendPropertyChanging();
					this._ChucVuHienTai = value;
					this.SendPropertyChanged("ChucVuHienTai");
					this.OnChucVuHienTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DuAn", Storage="_DuAns", ThisKey="MaNhanVien", OtherKey="MaDoiTruong")]
		public EntitySet<DuAn> DuAns
		{
			get
			{
				return this._DuAns;
			}
			set
			{
				this._DuAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DuAn1", Storage="_DuAns1", ThisKey="MaNhanVien", OtherKey="MaNguoiLapHoSo")]
		public EntitySet<DuAn> DuAns1
		{
			get
			{
				return this._DuAns1;
			}
			set
			{
				this._DuAns1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_NhanVien_DuAn", Storage="_NhanVien_DuAns", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<NhanVien_DuAn> NhanVien_DuAns
		{
			get
			{
				return this._NhanVien_DuAns;
			}
			set
			{
				this._NhanVien_DuAns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DuAns(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_DuAns(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_DuAns1(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = this;
		}
		
		private void detach_DuAns1(DuAn entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = null;
		}
		
		private void attach_NhanVien_DuAns(NhanVien_DuAn entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_NhanVien_DuAns(NhanVien_DuAn entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien_DuAn")]
	public partial class NhanVien_DuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhanVien;
		
		private int _MaDuAn;
		
		private string _CapBac;
		
		private string _ChucVu;
		
		private EntityRef<DuAn> _DuAn;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnMaDuAnChanging(int value);
    partial void OnMaDuAnChanged();
    partial void OnCapBacChanging(string value);
    partial void OnCapBacChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public NhanVien_DuAn()
		{
			this._DuAn = default(EntityRef<DuAn>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					if (this._DuAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDuAnChanging(value);
					this.SendPropertyChanging();
					this._MaDuAn = value;
					this.SendPropertyChanged("MaDuAn");
					this.OnMaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapBac", DbType="NVarChar(200)")]
		public string CapBac
		{
			get
			{
				return this._CapBac;
			}
			set
			{
				if ((this._CapBac != value))
				{
					this.OnCapBacChanging(value);
					this.SendPropertyChanging();
					this._CapBac = value;
					this.SendPropertyChanged("CapBac");
					this.OnCapBacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(200)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAn_NhanVien_DuAn", Storage="_DuAn", ThisKey="MaDuAn", OtherKey="MaDuAn", IsForeignKey=true)]
		public DuAn DuAn
		{
			get
			{
				return this._DuAn.Entity;
			}
			set
			{
				DuAn previousValue = this._DuAn.Entity;
				if (((previousValue != value) 
							|| (this._DuAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAn.Entity = null;
						previousValue.NhanVien_DuAns.Remove(this);
					}
					this._DuAn.Entity = value;
					if ((value != null))
					{
						value.NhanVien_DuAns.Add(this);
						this._MaDuAn = value.MaDuAn;
					}
					else
					{
						this._MaDuAn = default(int);
					}
					this.SendPropertyChanged("DuAn");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_NhanVien_DuAn", Storage="_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.NhanVien_DuAns.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.NhanVien_DuAns.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class lay_cottenduanResult
	{
		
		private string _tenduan;
		
		public lay_cottenduanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenduan", DbType="NVarChar(200)")]
		public string tenduan
		{
			get
			{
				return this._tenduan;
			}
			set
			{
				if ((this._tenduan != value))
				{
					this._tenduan = value;
				}
			}
		}
	}
	
	public partial class lay_cottennhanvienResult
	{
		
		private string _tennhanvien;
		
		public lay_cottennhanvienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NVarChar(200)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this._tennhanvien = value;
				}
			}
		}
	}
	
	public partial class laybangduanResult
	{
		
		private System.Nullable<int> _MaDuAn;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private System.Nullable<int> _MaDoiTruong;
		
		private System.Nullable<int> _MaNguoiLapHoSo;
		
		private string _TenDoiTruong;
		
		private string _TenNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		public laybangduanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int")]
		public System.Nullable<int> MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this._TenDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this._DienTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this._GiaTriHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this._GiaTriThanhQuyetToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTruong", DbType="Int")]
		public System.Nullable<int> MaDoiTruong
		{
			get
			{
				return this._MaDoiTruong;
			}
			set
			{
				if ((this._MaDoiTruong != value))
				{
					this._MaDoiTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiLapHoSo", DbType="Int")]
		public System.Nullable<int> MaNguoiLapHoSo
		{
			get
			{
				return this._MaNguoiLapHoSo;
			}
			set
			{
				if ((this._MaNguoiLapHoSo != value))
				{
					this._MaNguoiLapHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoiTruong", DbType="NVarChar(200)")]
		public string TenDoiTruong
		{
			get
			{
				return this._TenDoiTruong;
			}
			set
			{
				if ((this._TenDoiTruong != value))
				{
					this._TenDoiTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiLapHoSo", DbType="NVarChar(200)")]
		public string TenNguoiLapHoSo
		{
			get
			{
				return this._TenNguoiLapHoSo;
			}
			set
			{
				if ((this._TenNguoiLapHoSo != value))
				{
					this._TenNguoiLapHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this._FileDinhKem = value;
				}
			}
		}
	}
	
	public partial class laybangnhanvienResult
	{
		
		private System.Nullable<int> _manhanvien;
		
		private string _tennhanvien;
		
		private string _capbachientai;
		
		private string _chucvuhientai;
		
		private string _tentrangthai;
		
		public laybangnhanvienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="Int")]
		public System.Nullable<int> manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					this._manhanvien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NVarChar(200)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this._tennhanvien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capbachientai", DbType="NVarChar(200)")]
		public string capbachientai
		{
			get
			{
				return this._capbachientai;
			}
			set
			{
				if ((this._capbachientai != value))
				{
					this._capbachientai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucvuhientai", DbType="NVarChar(200)")]
		public string chucvuhientai
		{
			get
			{
				return this._chucvuhientai;
			}
			set
			{
				if ((this._chucvuhientai != value))
				{
					this._chucvuhientai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentrangthai", DbType="NVarChar(200)")]
		public string tentrangthai
		{
			get
			{
				return this._tentrangthai;
			}
			set
			{
				if ((this._tentrangthai != value))
				{
					this._tentrangthai = value;
				}
			}
		}
	}
	
	public partial class timkiem_namResult
	{
		
		private int _MaDuAn;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private System.Nullable<int> _MaDoiTruong;
		
		private System.Nullable<int> _MaNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		public timkiem_namResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int NOT NULL")]
		public int MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this._TenDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this._DienTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this._GiaTriHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this._GiaTriThanhQuyetToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTruong", DbType="Int")]
		public System.Nullable<int> MaDoiTruong
		{
			get
			{
				return this._MaDoiTruong;
			}
			set
			{
				if ((this._MaDoiTruong != value))
				{
					this._MaDoiTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiLapHoSo", DbType="Int")]
		public System.Nullable<int> MaNguoiLapHoSo
		{
			get
			{
				return this._MaNguoiLapHoSo;
			}
			set
			{
				if ((this._MaNguoiLapHoSo != value))
				{
					this._MaNguoiLapHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this._FileDinhKem = value;
				}
			}
		}
	}
	
	public partial class timkiem_tenduanResult
	{
		
		private int _MaDuAn;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private System.Nullable<int> _MaDoiTruong;
		
		private System.Nullable<int> _MaNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		public timkiem_tenduanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int NOT NULL")]
		public int MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this._TenDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this._DienTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this._GiaTriHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this._GiaTriThanhQuyetToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTruong", DbType="Int")]
		public System.Nullable<int> MaDoiTruong
		{
			get
			{
				return this._MaDoiTruong;
			}
			set
			{
				if ((this._MaDoiTruong != value))
				{
					this._MaDoiTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiLapHoSo", DbType="Int")]
		public System.Nullable<int> MaNguoiLapHoSo
		{
			get
			{
				return this._MaNguoiLapHoSo;
			}
			set
			{
				if ((this._MaNguoiLapHoSo != value))
				{
					this._MaNguoiLapHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this._FileDinhKem = value;
				}
			}
		}
	}
	
	public partial class lay_bangduanResult
	{
		
		private System.Nullable<int> _MaDuAn;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private string _TenDoiTruong;
		
		private string _TenNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		public lay_bangduanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int")]
		public System.Nullable<int> MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this._TenDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this._DienTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this._GiaTriHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this._GiaTriThanhQuyetToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoiTruong", DbType="NVarChar(200)")]
		public string TenDoiTruong
		{
			get
			{
				return this._TenDoiTruong;
			}
			set
			{
				if ((this._TenDoiTruong != value))
				{
					this._TenDoiTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiLapHoSo", DbType="NVarChar(200)")]
		public string TenNguoiLapHoSo
		{
			get
			{
				return this._TenNguoiLapHoSo;
			}
			set
			{
				if ((this._TenNguoiLapHoSo != value))
				{
					this._TenNguoiLapHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this._FileDinhKem = value;
				}
			}
		}
	}
	
	public partial class lay_bangduan1Result
	{
		
		private System.Nullable<int> _MaDuAn;
		
		private int _STT;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private string _TenDoiTruong;
		
		private string _TenNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		public lay_bangduan1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int")]
		public System.Nullable<int> MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this._TenDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this._DienTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this._GiaTriHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this._GiaTriThanhQuyetToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoiTruong", DbType="NVarChar(200)")]
		public string TenDoiTruong
		{
			get
			{
				return this._TenDoiTruong;
			}
			set
			{
				if ((this._TenDoiTruong != value))
				{
					this._TenDoiTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiLapHoSo", DbType="NVarChar(200)")]
		public string TenNguoiLapHoSo
		{
			get
			{
				return this._TenNguoiLapHoSo;
			}
			set
			{
				if ((this._TenNguoiLapHoSo != value))
				{
					this._TenNguoiLapHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this._FileDinhKem = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
